spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/runmvp}
    username: ${DB_USERNAME:runmvp}
    password: ${DB_PASSWORD:runmvp}
    driver-class-name: org.postgresql.Driver
  main:
    web-application-type: none

worker:
  statistics:
    poll-interval-ms: 10000
