package com.runmvp.shared.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    // Auth
    GOOGLE_TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    REFRESH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED),
    REFRESH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
    ACCOUNT_DELETED(HttpStatus.UNAUTHORIZED),
    // User
    USER_NOT_FOUND(HttpStatus.NOT_FOUND),
    // Friends
    CANNOT_FRIEND_SELF(HttpStatus.BAD_REQUEST),
    FRIEND_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND),
    NOT_REQUEST_RECIPIENT(HttpStatus.FORBIDDEN),
    FRIENDSHIP_ALREADY_EXISTS(HttpStatus.CONFLICT),
    FRIEND_REQUEST_ALREADY_PENDING(HttpStatus.CONFLICT),
    FRIENDSHIP_NOT_FOUND(HttpStatus.NOT_FOUND),
    // Sessions
    SESSION_NOT_FOUND(HttpStatus.NOT_FOUND),
    NOT_SESSION_MEMBER(HttpStatus.FORBIDDEN),
    NOT_SESSION_CREATOR(HttpStatus.FORBIDDEN),
    NOT_INVITED(HttpStatus.FORBIDDEN),
    INVITE_EXPIRED(HttpStatus.CONFLICT),
    SESSION_ALREADY_STARTED(HttpStatus.CONFLICT),
    SESSION_FULL(HttpStatus.CONFLICT),
    INVALID_INVITEE_COUNT(HttpStatus.BAD_REQUEST),
    NOT_FRIENDS(HttpStatus.BAD_REQUEST),
    INVALID_DISTANCE(HttpStatus.BAD_REQUEST),
    INVALID_SESSION_STATE(HttpStatus.CONFLICT),
    NO_ACCEPTED_PARTICIPANTS(HttpStatus.CONFLICT),
    HAS_ACCEPTED_PARTICIPANTS(HttpStatus.CONFLICT),
    PARTICIPANT_NOT_FOUND(HttpStatus.NOT_FOUND),
    INVALID_SESSION_DISTANCE(HttpStatus.BAD_REQUEST),
    NOT_SESSION_PARTICIPANT(HttpStatus.NOT_FOUND),
    ALREADY_SESSION_PARTICIPANT(HttpStatus.CONFLICT),
    // Running
    SESSION_NOT_IN_PROGRESS(HttpStatus.CONFLICT),
    BATCH_TOO_LARGE(HttpStatus.BAD_REQUEST),
    GOAL_NOT_REACHED(HttpStatus.CONFLICT),
    RESULT_NOT_READY(HttpStatus.CONFLICT),
    // Monetization
    PREMIUM_REQUIRED(HttpStatus.FORBIDDEN),
    PURCHASE_TOKEN_INVALID(HttpStatus.BAD_REQUEST),
    PURCHASE_TOKEN_ALREADY_LINKED(HttpStatus.CONFLICT),
    // Generic
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST),
    RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR);

    private final HttpStatus httpStatus;

    ErrorCode(HttpStatus httpStatus) { this.httpStatus = httpStatus; }

    public HttpStatus getHttpStatus() { return httpStatus; }
}
